datarobot-oss/qa-app-streamlit

- .github/CONTRIBUTING.md
> Fix Contributing maintainers

- .github/workflows/notify-slack.yml
- .github/workflows/reminder.yml
- .github/workflows/remove-label-when-approved.yml
- CODEOWNERS
We (maintainers) should be aware of any PRs that are waiting for reviews
- Add workflow for sending slack message when 'Ready for review' label has been added
- Add workflow for reminding about pending PR reviews every 3 hrs (AFAIK will not be active until it is merged to main)
- Remove label once PR has been approved
- Update the CODEOWNERS file
> Add Slack + Github actions and fix CODEOWNERS file

- CODEOWNERS
- src/components.py
- template_info.json
Currently the footer will hide If there is no meta info. Show it as long as the citations are available 
- Fix codeowners/env name
- Add citations/info_data conditions
> [Yolo-bug] Show footer citations when no other info data is available

- src/metadata.yaml
- template_info.json
Make the deployment selection easier by using the `deployment` param type
> [APP-3386] Change param type to deployment

- src/dr_requests.py
- template_info.json
We hardcoded the resultText column name, instead use the deployment target_name
> [APP-3393] Change hardcoded resultText to use target_name from deployment

- src/dr_requests.py
Sending integers as prompt cause an error as they seem to be inferred to wrong type  
- Force quotes on the prompt value
> [APP-3402] Force prompt to be string using quotes

- src/components.py
- src/constants.py
- src/qa_chat_bot.py
- src/utils.py
There is currently no guidance and user friendly errors when deployment id is missing or the deployment was not found
- Add error for both cases
> [APP-3408] Add error for missing deployment_id and not found deployment

- src/dr_requests.py
For our On-Prem and ST SAAS customers in 10.2 we will need to override the prediction server URL. The clusters we have 
there have very bespoke network policies, and at the moment there is limited egress. 
I chose to determine whether we were on-prem or not by testing the public API URL for two reasons:
1. If the app needs to send requests to the  `datarobot-nginx` service instead of the public API, it probably needs to send requests to via the`datarobot-prediction-server` service URL. 
2. If we change the network policies in the future and are free to access the prediction server through the app's regular host, and we adjust the `DATAROBOT_ENDPOINT` inside the logic which controls app environment provisioning, we  won't break this template. 
I tested this in the EKS regression …
> [APP-3461] Add override URL for on-prem / ST SAAS

- README.md
- src/constants.py
- src/dr_requests.py
- src/utils.py
If Deployment association ID is set to `promptText` it will overwrite the actual prompt and break the app. Fix it and add better README
- Refactor column name getter
- Set promptText after assoc id to avoid overwriting it even with misconfigured deployment
- Add better readme section for custom metric / assoc id
- Add troubleshooting section with common errors and solutions
> [APP-3335] Fix predict columns when assoc id is same as prompt column

- src/components.py
- src/utils.py
LLM responses with multiple $ characters would be shown as LaTex format. Escape $ symbols to avoid it
> [APP-3463] Fix unexpected LaTex formatting by escaping $ symbol

- template_info.json
The base execution environment is getting renamed. Update the template_info and bump the version
> [APP-3468] QA chat template: Rename exec env 3.12 App Base and bump version

- src/components.py
- src/utils.py
- template_info.json
The association ID is considered an optional setting for the LLM deployment that is used in the Q&A app.
It should not give any exceptions when not set
- Fix get_association_id_column_name function
- Hide feedback buttons when assoc id is not set
- Bump version
> [APP-3490] Fix error when assoc id is not set

- src/components.py
- src/utils.py
- template_info.json
BACKPORT 
The association ID is considered an optional setting for the LLM deployment that is used in the Q&A app.
It should not give any exceptions when not set
- Fix get_association_id_column_name function
- Hide feedback buttons when assoc id is not set
- Bump version
> [APP-3490] Backport 10.2: Fix error when assoc id is not set

- template_info.json
The execution env name was only updated in 10.2 branch - fix it on main too!
> [Yolo] Fix exec env name on main branch

- src/constants.py
- src/dr_requests.py
- src/qa_chat_bot.py
- src/utils.py
- tests/conftest.py
- tests/test_qa_chat_bot.py
In preparation for Chat API we need to detect whether the deployment even supports it. 
- Add deployment capabilities call
- Check for chat api support
> [APP-3527] Detect Chat API support from deployment capabilities

- src/components.py
- src/constants.py
- src/dr_requests.py
- src/qa_chat_bot.py
- src/utils.py
- tests/test_qa_chat_bot.py
To prepare for streaming chat api we need to refactor how we treat the conversation context and relevant meta data for each message.
The existing predict implementation should continue working as before
- Split message role/content apart from any other meta data
- Refactor how the prediction request is made so it can be swapped with streaming request later
- Force disable chat api until it is fully implemented
> [APP-3526] Refactor messages and meta state in preparation for Chat API

- src/components.py
- src/dr_requests.py
- src/utils.py
required
This PR implements a new `send_stream_request` that makes use of the chat/completion endpoint from a deployment that supports it. 
The existing approach with datarobot-predict will continue to work for any unsupported deployments
- Pull common processing utils out so that both the new `send_stream_request` and existing `send_predict_request` can make use of it
- Change process_citations to return the desired data structure directly
- Strip meta_id from context messages to not fail OpenAI schema
> [APP-3528] Implement streaming request using chat api on supported deployment

- src/constants.py
- src/dr_requests.py
User should be able to control stream on/off. We should handle both types of responses properly
- Add new const to control streaming
- Fix response handling when stream is False
> [APP-3625] Allow user to disable streaming and fix response handling

- src/components.py
- src/constants.py
- src/metadata.yaml
- src/qa_chat_bot.py
- src/start-app.sh
- src/utils.py
- tests/conftest.py
- tests/test_qa_chat_bot.py
For RAG assistant we would like to rename the application using runtime params
> [APP-3640] Add app name as runtime param, include existing title as default

- src/constants.py
- template_info.json
- tests/test_qa_chat_bot.py
The work for Chat API has been completed, now we can enable it by default and bump the template version
> [APP-3662] Enable Chat API by default, bump template version

- README.md
- src/metadata.yaml
- src/start-app.sh
- src/utils.py
- template_info.json
Users should be able to configure a system prompt for the Chat API
Values for this parameter will override any previous prompts, even the one set in DR > Workbench > Playground
- Add new runtime param SYSTEM_PROMPT
- Append any value as first entry in session messages
- Update readme
- Bump version
> [APP-3676] Add support for system prompt

- src/components.py
- src/dr_requests.py
- src/utils.py
- template_info.json
- tests/mocks/mock_chat_api_no_stream.json
- tests/mocks/mock_final_chunk.json
- tests/test_qa_chat_bot.py
QA App broke for a deployment without moderations due to process citations function looking for the moderations result. Instead use the .citations on the completion
> [APP-3686] Fix citations for deployments without moderation

- src/constants.py
- src/dr_requests.py
- template_info.json
- tests/test_qa_chat_bot.py
We are facing issues with some LLMs on prod. Better to revert the default enabler for now
> [APP-3688] Revert chat api enable by default

- README.md
- src/components.py
- src/constants.py
- src/dr_requests.py
- template_info.json
- tests/conftest.py
- tests/mocks/mock_chat_api_no_stream.json
- tests/mocks/mock_final_chunk.json
- tests/mocks/mock_initial_chunk.json
- tests/test_qa_chat_bot.py
Streaming should not be enabled by default as we currently only support GPT blueprints for it.
Furthermore the stream value should not be set at all - not even as False/None
Error handling has been improved to make it more clear when the error happened during a request or within the app.
Requests will show url and code/reason/message while processing issues show `Error while processing response from Chat API: ..<error message>`
- Fix stream value by not sending a value at all for False/None
- Improve error messages (server/endpoint vs app error)
- Improve docs with streaming limitations
- Disable streaming as default setting
- Fix loading message for non-streaming chat api requests 
- Re-enable Chat API default to true
- Add new (complete) mocks for tests
- Bump the template version …
> [APP-3696] Fix streaming value and improve error messages

- src/constants.py
- template_info.json
- tests/test_qa_chat_bot.py
Force disable Chat API and bump template version
> [APP-3718] Force disable Chat Api (again)

- src/components.py
- src/dr_requests.py
- src/requirements.txt
- src/utils.py
- tests/conftest.py
- tests/test_qa_chat_bot.py
To match our Datarobot documentation for Chat API we should use the openai client to make the requests.
https://docs.datarobot.com/en/docs/gen-ai/genai-chat-completion-api.html
- Split streaming and non-streaming requests into separate functions
- Use openai client to make the requests to the deployment
> [APP-3739] Refactor Chat API requests to use openai client

- README.md
- src/components.py
- src/constants.py
- src/metadata.yaml
- src/qa_chat_bot.py
- src/start-app.sh
- src/utils.py
- tests/conftest.py
- tests/test_qa_chat_bot.py
Make it easier for users to flip Chat API and streaming on/off by moving the values to runtime params
> [APP-3754] Change chat api constants to runtime params

- template_info.json
> [APP-3775] Bump app template version

- src/metadata.yaml
It wasnt clear that streaming and system prompt only work then chat api is enabled. Improve the descriptions for the params
> [APP-3806] Improve Chat Api runtime param descriptions

- src/components.py
- src/dr_requests.py
- template_info.json
When assoc id was auto generated we continued to use a message meta id instead of the already generated association id. 
- Attempt to use existing assoc id before falling back to message meta id
> [APP-4102] Fix association id for feedback custom metric

- template_info.json
Bump main branch version for Q&A template, new release 11.1 branch has been created: 
https://github.com/datarobot-oss/qa-app-streamlit/tree/releases/11.1
> Bump main branch version to 11.2

- .gitignore
- src/dr_requests.py
- src/start-app.sh
- src/utils.py
- tests/conftest.py
Since june the split on STREAMLIT_SERVER_BASE_URL_PATH we used to get app_id no longer worked. There was a trailing slash added. Instead of splitting these things we can use the APPLICATION_ID added beginning of the year
_In general, what was changed? Screenshots are welcome too!_
> [APP-4672] Use another env var for app id -> app info call

- src/dr_requests.py
- template_info.json
A user saw duplicate responses when using chat api + streaming, to guard against it we can make sure to return after the final chunk (finish_reason=stop)
_In general, what was changed? Screenshots are welcome too!_
> [APP-4012] Make sure we dont see duplicate responses for misconfigured NIM llm
